//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SC_Tools.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SC_Tools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 65.116.88.30.
        /// </summary>
        internal static string Host {
            get {
                return ResourceManager.GetString("Host", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGEDIT4
        ///
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\WOW6432Node\JosephTest]
        ///&quot;TestKey1&quot;=&quot;0&quot;
        ///&quot;TestKey2&quot;=dword:00000001.
        /// </summary>
        internal static string JTest1 {
            get {
                return ResourceManager.GetString("JTest1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SC%ftp01!.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to scftp.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to REGEDIT4
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\Internet Settings]
        ///&quot;MinorVersion&quot;=&quot;0&quot;
        ///&quot;CodeBaseSearchPath&quot;=&quot;CODEBASE;&lt;http://codecs.microsoft.com/isapi/ocget.dll&gt;&quot;
        ///&quot;UrlEncoding&quot;=&quot;0x00000000&quot;
        ///&quot;ActiveXCache&quot;=&quot;C:\\WINDOWS\\Downloaded Program Files&quot;
        ///&quot;EnablePunycode&quot;=dword:00000001
        ///&quot;WarnOnIntranet&quot;=dword:00000001
        ///&quot;ProxyEnable&quot;=dword:00000000
        ///&quot;ProxyOverride&quot;=-
        ///&quot;ProxyServer&quot;=-
        ///
        ///[HKEY_LOCAL_MACHINE\SOFTWARE\Wow6432Node\Microsoft\Windows\CurrentVersion\Internet Settings]
        ///&quot;ProxyE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string windows_proxy_fix {
            get {
                return ResourceManager.GetString("windows_proxy_fix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to C:\SCTools2021\win_reg_fix.reg.
        /// </summary>
        internal static string WindowsRegFix {
            get {
                return ResourceManager.GetString("WindowsRegFix", resourceCulture);
            }
        }
    }
}
